var fs = require('fs');
var request = require('request');

module.exports = (dato, root) => {
  const pages = {};
  dato.pages.map( page => 
    Object.assign(
      pages,
      {[`${page.id}`]:{
        title:page.title,
        slug:page.slug
      }})
  )
  root.createDataFile(
    'pages/_site.json',
    'json',
    {
      site: dato.site.toMap(),
      start: dato.start.toMap(),
      impressum:dato.impressum.toMap(),
      pages: pages 
    }
    );

  // dato.singleInstanceItemTypes.forEach(itemType => {
  //   const item = dato.itemsOfType(itemType)[0];
  //   if (item) {
  //     root.createDataFile(`pages/source/_data/${itemType.apiKey}.yml`, 'yaml', item.toMap());
  //   }
  // });

  // dato.collectionItemTypes.forEach(itemType => {
  //   root.directory(`pages/source/_${itemType.apiKey}/`, dir => {
  //     dato.itemsOfType(itemType).forEach(item => {
  //       dir.createPost(`${item.autogeneratedSlug()}.md`, 'yaml', { frontmatter: item.toMap() });
  //     });
  //   });
  // // });
  // let pages;
  // dato.pages.map( page => Object.assign(pages,{slug:page.slug}))

  dato.pages.forEach( page => {
    root.createPost(
        `./pages/${page.slug}.md`,
        'yaml',
        {
          frontmatter: {
            id:page.id,
            title:page.title,
            slug:page.slug
          },
          content: page.body}
    )
  })
};